services:
  - type: web
    name: learning-logs
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ll_project001.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_SETTINGS_MODULE
        value: ll_project001.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: your-service-name.onrender.com
      - key: DATABASE_URL
        sync: false
