services:
  - type: web
    name: learning-logs
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn ll_project.wsgi:application --bind 0.0.0.0:$PORT
